version: "3.8"
services:
  postgresdb:
    image: postgres:15-alpine
    container_name: pet-care-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      # POSTGRES_DB: pet_care
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - auth-service
      
  user-service:
    build: ./services/user-service
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - ./services/user-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
  
  pet-service:
    build: ./services/pet-service
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./services/pet-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
volumes:
  postgres_data:
