version: "3.8"

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: pet-care-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pet-network 

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - pet-network 

  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
    networks:
      - pet-network 

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./services/api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - auth-service
    networks:
      - pet-network 

  user-service:
    build: ./services/user-service
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - ./services/user-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
    networks:
      - pet-network

  pet-service:
    build: ./services/pet-service
    env_file:
      - .env
    ports:
      - "3003:3003"
    volumes:
      - ./services/pet-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
    networks:
      - pet-network 

  notification-service:
    build: ./services/notification-service
    env_file:
      - .env
    ports:
      - "3004:3004"
    volumes:
      - ./services/notification-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
      - redis
    networks:
      - pet-network 
  
  vaccine-service:
    build: ./services/vaccine-service
    env_file:
      - .env
    ports:
      - "3005:3005"
    volumes:
      - ./services/vaccine-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgresdb
      - redis
    networks:
      - pet-network 

networks:
  pet-network:
    driver: bridge

volumes:
  postgres_data: